In [20]:
import os
os.environ['HF_HOME'] = '/scr/vvajipey/.cache/huggingface'
os.environ['HF_HUB'] = '/scr/vvajipey/.cache/huggingface'
from huggingface_hub import login
login("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")

import ast
import numpy as np
import os
import pandas as pd
import torch
from collections import Counter, defaultdict
from difflib import get_close_matches
from dotenv import load_dotenv
from openai import OpenAI
from pprint import pprint
import random
import re
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
from transformers import StoppingCriteria, StoppingCriteriaList
import torch.nn.functional as F

# gsm_df = pd.read_csv('../distribution/data/gsm8kTest.csv')

model_name = "mistralai/Mistral-7B-Instruct-v0.1"
# model_name = "mistralai/Mistral-7B-Instruct-v0.3"
# model_name = "meta-llama/Meta-Llama-3-8B"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = 'left'

model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.bfloat16, device_map="auto")
model.generation_config = GenerationConfig.from_pretrained(model_name)
model.generation_config.pad_token_id = model.generation_config.eos_token_id

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /scr/vvajipey/.cache/huggingface/token
Login successful


/scr/vvajipey/miniconda3/envs/reason/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [3]:
import ast
train_df = pd.read_csv("data/commonsense_qa_train.csv")
train_df['choices'] = train_df['choices'].apply(ast.literal_eval)
# train_df



In [15]:
def sample_completions_from_model(question, choices, tokenizer, n_samples=1):
    # https://arxiv.org/html/2402.17302v1
    
    prompt = f"""Question: {question}
    Choices:
    A. {choices[0]}
    B. {choices[1]}
    C. {choices[2]}
    D. {choices[3]}
    E. {choices[4]}
    Answer:"""
    chat = [{"role":"user", "content":prompt}]

    input_tensor = tokenizer.apply_chat_template(chat)

    for _ in range(n_samples):
        gen_outputs = model.generate(
            input_tensor.to(model.device),
            min_new_tokens=10,
            max_new_tokens=1000,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=True,
            temperature=0.7,
            top_k=40,
        ).sequences
    return new_paths, path_to_tensor

In [4]:
train_df['choices'][1]['text']

['race track', 'populated areas', 'the desert', 'apartment', 'roadblock']

In [5]:
prompt = f"""Question: {train_df['question'][1]}
    Choices:
    (A) {train_df['choices'][1]['text'][0]}
    (B) {train_df['choices'][1]['text'][1]}
    (C) {train_df['choices'][1]['text'][2]}
    (D) {train_df['choices'][1]['text'][3]}
    (E) {train_df['choices'][1]['text'][4]}
    Answer:"""
prompt

'Question: Sammy wanted to go to where the people were.  Where might he go?\n    Choices:\n    (A) race track\n    (B) populated areas\n    (C) the desert\n    (D) apartment\n    (E) roadblock\n    Answer:'

In [6]:
chat = [{"role":"user", "content":prompt}]

input_tensor = tokenizer.apply_chat_template(chat, return_tensors='pt')
tokenizer.apply_chat_template(chat, tokenize=False) 

'<s>[INST] Question: Sammy wanted to go to where the people were.  Where might he go?\n    Choices:\n    (A) race track\n    (B) populated areas\n    (C) the desert\n    (D) apartment\n    (E) roadblock\n    Answer: [/INST]'

In [29]:
gen_outputs = model.generate(
            input_tensor.to(model.device),
            min_new_tokens=10,
            max_new_tokens=1000,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=True,
            temperature=0.7,
            top_k=40,
        )

In [30]:
pprint(tokenizer.batch_decode(gen_outputs.sequences))

['<s> [INST] Question: Sammy wanted to go to where the people were.  Where '
 'might he go?\n'
 '    Choices:\n'
 '    (A) race track\n'
 '    (B) populated areas\n'
 '    (C) the desert\n'
 '    (D) apartment\n'
 '    (E) roadblock\n'
 '    Answer: [/INST] Sammy might go to where the people are, so the correct '
 'choice would be (B) populated areas.</s>']


In [31]:
transition_scores = model.compute_transition_scores(
    gen_outputs.sequences, gen_outputs.scores, normalize_logits=True
)
transition_scores

tensor([[-1.2758e-01,  0.0000e+00, -3.8946e-01, -1.9602e-02, -5.8768e-05,
         -3.8944e+00, -1.0339e-01, -2.3374e-04, -1.1094e-01, -9.0137e-02,
         -3.1514e-01, -1.1663e-01, -1.7940e+00, -1.5629e-01, -2.5322e-01,
         -1.7047e-05, -3.9002e-03, -1.9322e-03, -1.1921e-07, -5.1259e-05,
          0.0000e+00,  0.0000e+00, -1.9518e-03, -2.8916e-04]], device='cuda:0')

In [33]:
input_length = input_tensor.shape[1]
input_length

71

In [36]:
generated_tokens = gen_outputs.sequences[:, input_length:]
for tok, score in zip(generated_tokens[0], transition_scores[0]):
    # | token | token string | logits | probability
    print(f"| {tok:5d} | {tokenizer.decode(tok):8s} | {score.cpu().numpy():.4f} | {np.exp(score.cpu().numpy()):.2%}")

|  4157 | Sam      | -0.1276 | 88.02%
|  1916 | my       | 0.0000 | 100.00%
|  1659 | might    | -0.3895 | 67.74%
|   576 | go       | -0.0196 | 98.06%
|   298 | to       | -0.0001 | 99.99%
|   970 | where    | -3.8944 | 2.04%
|   272 | the      | -0.1034 | 90.18%
|   905 | people   | -0.0002 | 99.98%
|   460 | are      | -0.1109 | 89.50%
| 28725 | ,        | -0.0901 | 91.38%
|   579 | so       | -0.3151 | 72.97%
|   272 | the      | -0.1166 | 88.99%
|  4714 | correct  | -1.7940 | 16.63%
|  4782 | choice   | -0.1563 | 85.53%
|   682 | would    | -0.2532 | 77.63%
|   347 | be       | -0.0000 | 100.00%
|   325 | (        | -0.0039 | 99.61%
| 28760 | B        | -0.0019 | 99.81%
| 28731 | )        | -0.0000 | 100.00%
|  1852 | pop      | -0.0001 | 99.99%
|  6432 | ulated   | 0.0000 | 100.00%
|  5020 | areas    | 0.0000 | 100.00%
| 28723 | .        | -0.0020 | 99.81%
|     2 | </s>     | -0.0003 | 99.97%


In [47]:
letters = tokenizer.encode("(A)_(B)_(C)_(D)_(E)\n A A\n An Answer a B C D E")
for tok in letters:
    print(f"{tok} = '{tokenizer.decode(tok)}'")

1 = '<s>'
325 = '('
28741 = 'A'
28731 = ')'
10653 = '_('
28760 = 'B'
28731 = ')'
10653 = '_('
28743 = 'C'
28731 = ')'
10653 = '_('
28757 = 'D'
28731 = ')'
10653 = '_('
28749 = 'E'
28731 = ')'
13 = '
'
330 = 'A'
330 = 'A'
13 = '
'
1094 = 'An'
26307 = 'Answer'
264 = 'a'
365 = 'B'
334 = 'C'
384 = 'D'
413 = 'E'


In [50]:
output_tensor = gen_outputs.sequences

answer_to_tok = {'A':[28741, 330], 'B':[28760, 365], 'C':[28743, 334], 'D':[28757, 384], 'E':[28749, 413]}

masked_output_tensor = torch.where(
    torch.isin(output_tensor, torch.tensor(answer_to_tok['B'], device=output_tensor.device)),
    output_tensor,
    torch.tensor(0, device=output_tensor.device)
)
masked_output_tensor

tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0, 28760,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0, 28760,     0,
             0,     0,     0,     0,     0]], device='cuda:0')

In [52]:
generated_tokens = masked_output_tensor[:, input_length:]
for tok, score in zip(generated_tokens[0], transition_scores[0]):
    # | token | token string | logits | probability
    print(f"| {tok:5d} | {tokenizer.decode(tok):8s} | {score.cpu().numpy():.4f} | {np.exp(score.cpu().numpy()):.2%}")

|     0 | <unk>    | -0.1276 | 88.02%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | -0.3895 | 67.74%
|     0 | <unk>    | -0.0196 | 98.06%
|     0 | <unk>    | -0.0001 | 99.99%
|     0 | <unk>    | -3.8944 | 2.04%
|     0 | <unk>    | -0.1034 | 90.18%
|     0 | <unk>    | -0.0002 | 99.98%
|     0 | <unk>    | -0.1109 | 89.50%
|     0 | <unk>    | -0.0901 | 91.38%
|     0 | <unk>    | -0.3151 | 72.97%
|     0 | <unk>    | -0.1166 | 88.99%
|     0 | <unk>    | -1.7940 | 16.63%
|     0 | <unk>    | -0.1563 | 85.53%
|     0 | <unk>    | -0.2532 | 77.63%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0039 | 99.61%
| 28760 | B        | -0.0019 | 99.81%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0001 | 99.99%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | -0.0020 | 99.81%
|     0 | <unk>    | -0.0003 | 99.97%


In [54]:
transition_scores.shape

torch.Size([1, 24])

In [55]:
generated_tokens.shape

torch.Size([1, 24])

In [53]:
non_zero_values = masked_output_tensor[masked_output_tensor != 0]
non_zero_values

tensor([28760, 28760], device='cuda:0')

In [60]:
answer_mask = torch.isin(generated_tokens, torch.tensor(answer_to_tok['B'], device=output_tensor.device)).int()
masked_generated_tokens = generated_tokens * answer_mask
masked_generated_tokens

tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0, 28760,     0,     0,
             0,     0,     0,     0]], device='cuda:0')

In [63]:
masked_log_probs = transition_scores * answer_mask
for tok, score in zip(masked_generated_tokens[0], masked_log_probs[0]):
    # | token | token string | logits | probability
    print(f"| {tok:5d} | {tokenizer.decode(tok):8s} | {score.cpu().numpy():.4f} | {np.exp(score.cpu().numpy()):.2%}")

|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
| 28760 | B        | -0.0019 | 99.81%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%


In [49]:
for c in "ABCDE":
    print(c)
    print(answer_to_tok[c])
    print(tokenizer.batch_decode(answer_to_tok[c]))

A
[28741, 330]
['A', 'A']
B
[28760, 365]
['B', 'B']
C
[28743, 334]
['C', 'C']
D
[28757, 384]
['D', 'D']
E
[28749, 413]
['E', 'E']


In [70]:
# b_tensor = tokenizer.batch_decode(tokenizer.encode(tokenizer.apply_chat_template(chat, tokenize=False) + " The answer is (B).", return_tensors='pt', add_special_tokens=False))
b_tensor = tokenizer.encode(tokenizer.apply_chat_template(chat, tokenize=False) + " The answer is (B).", return_tensors='pt', add_special_tokens=False)

In [71]:
b_outputs = model.generate(
            b_tensor.to(model.device),
            min_new_tokens=10,
            max_new_tokens=1000,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=True,
            temperature=0.7,
            top_k=40,
        )

In [76]:
tokenizer.batch_decode(b_outputs.sequences)

['<s> [INST] Question: Sammy wanted to go to where the people were.  Where might he go?\n    Choices:\n    (A) race track\n    (B) populated areas\n    (C) the desert\n    (D) apartment\n    (E) roadblock\n    Answer: [/INST] The answer is (B). Sammy wanted to go to where the people were, and the best option among the given choices is the populated areas, where he is likely to find a large number of people.</s>']

In [77]:
b_output_tensor = b_outputs.sequences

In [79]:
tokenizer.batch_decode(b_output_tensor[:, b_tensor.shape[1]:])

['Sammy wanted to go to where the people were, and the best option among the given choices is the populated areas, where he is likely to find a large number of people.</s>']

Pipeline

In [22]:
q_num = 1
n_samples = 3
answer_letter = 'B'

train_df = pd.read_csv("data/commonsense_qa_train.csv")
train_df['choices'] = train_df['choices'].apply(ast.literal_eval)

prompt = f"""Question: {train_df['question'][q_num]}
    Choices:
    (A) {train_df['choices'][q_num]['text'][0]}
    (B) {train_df['choices'][q_num]['text'][1]}
    (C) {train_df['choices'][q_num]['text'][2]}
    (D) {train_df['choices'][q_num]['text'][3]}
    (E) {train_df['choices'][q_num]['text'][4]}
    Answer:"""

chat = [{"role":"user", "content":prompt}]

answer_prefix = tokenizer.encode(tokenizer.apply_chat_template(chat, tokenize=False) + " The answer is (B).", return_tensors='pt', add_special_tokens=False)
input_tensor = answer_prefix.repeat(n_samples, 1)

outputs = model.generate(
            input_tensor.to(model.device),
            min_new_tokens=10,
            max_new_tokens=1000,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=True,
            temperature=0.7,
            top_k=40,
        )

In [23]:
full_answer = outputs.sequences
full_answer.shape

torch.Size([3, 109])

In [24]:
def find_last_occurrence(tensor, target, offset=2, repeated=False):
    mask = (tensor == target)
    last_occurrence_indices = []
    
    for i in range(tensor.shape[0]):
        indices = torch.nonzero(mask[i], as_tuple=False).squeeze()
        last_occurrence_index = -1
        if indices.numel() > 0:
            last_occurrence_index = indices[-1].item() + offset 
        last_occurrence_indices.append(last_occurrence_index)
        if repeated:
            return last_occurrence_indices * tensor.shape[0]
    
    return last_occurrence_indices

find_last_occurrence(full_answer, 16289)

[71, 71, 71]

In [25]:
def mask_before_last_occurrence(tensor, target, offset=2):
    last_occurrence_indices = find_last_occurrence(tensor, target, offset, repeated=True)
    
    mask = torch.ones_like(tensor, dtype=torch.bool)
    masked_tokens_count = []
    
    for i in range(tensor.shape[0]):
        if last_occurrence_indices[i] != -1:
            mask[i, :last_occurrence_indices[i]] = 0
            masked_count = last_occurrence_indices[i]
        else:
            masked_count = 0
        masked_tokens_count.append(masked_count)
    
    masked_tensor = tensor * mask
    
    return masked_tensor, mask, masked_tokens_count

In [26]:
answer_tensor, answer_mask, prefix_lengths = mask_before_last_occurrence(full_answer, 16289)
answer_tensor, tokenizer.batch_decode(answer_tensor[:, prefix_lengths[0]:])

(tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,   415,  4372,   349,   325, 28760,   609,  4157,  1916,  2613,
            298,   576,   298,   970,   272,   905,   654, 28725,   304,   272,
           1080,  3917,  1633,   354,   713,   298,  1300,   264, 15987,   302,
            905,   682,   347,   297,  1852,  6432,  5020, 28723,     2],
         [    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,  

In [27]:
torch.equal(answer_tensor, full_answer * answer_mask)

True

In [28]:
instruct_log_probs = model.compute_transition_scores(
    outputs.sequences, outputs.scores, normalize_logits=True
)
instruct_log_probs

tensor([[-2.0853e-03,  0.0000e+00, -1.0460e-01, -5.9605e-07, -2.1458e-06,
         -3.2986e-03, -6.2643e-01, -3.0676e-03, -3.0994e-06, -3.6955e-06,
         -2.9903e-03, -1.5433e+00, -5.1340e-02, -6.1138e-01, -1.4793e-01,
         -5.2463e-02, -1.4274e-01, -7.6380e-01, -5.9841e-05, -7.1613e-02,
         -1.5414e+00, -7.6814e-01, -4.7684e-07, -1.9431e-05, -6.6422e-02,
         -3.5763e-07, -3.1085e-04, -7.8949e-02, -1.1921e-07, -1.1921e-07,
         -2.1015e-02, -9.6928e-01],
        [-2.0853e-03,  0.0000e+00, -1.0460e-01, -5.9605e-07, -2.1458e-06,
         -3.2986e-03, -6.2643e-01, -3.0676e-03, -3.0994e-06, -3.6955e-06,
         -2.9903e-03, -2.9332e-01, -3.0152e-01, -1.0032e+00, -3.9964e-01,
         -1.0010e-01, -4.0173e-05, -2.2662e+00,  0.0000e+00,  0.0000e+00,
         -7.3189e-03, -3.7680e-02, -1.3303e-02, -8.2801e-03, -4.9709e-03,
         -1.6271e-03, -7.7468e-04, -3.7925e-04, -1.7224e-04, -1.0430e-04,
         -6.9973e-05, -6.5563e-05],
        [-2.0853e-03,  0.0000e+00, -1.04

In [29]:
torch.save(full_answer, f"tensors/full_answer_tensors/columbus-csqa_q{q_num}_a{answer_letter}_n{n_samples}_logprobs.pt")
torch.save(answer_mask, f"tensors/answer_masks/columbus-csqa_q{q_num}_a{answer_letter}_n{n_samples}_answer_mask.pt")
torch.save(instruct_log_probs, f"tensors/instruct_log_probs/columbus-csqa_q{q_num}_a{answer_letter}_n{n_samples}_instruct_logprobs.pt")

Assess Log Probs with Base Model

In [1]:
import os
os.environ['HF_HOME'] = '/scr/vvajipey/.cache/huggingface'
os.environ['HF_HUB'] = '/scr/vvajipey/.cache/huggingface'
from huggingface_hub import login
login("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")

import numpy as np
import os
import pandas as pd
import torch
from collections import Counter, defaultdict
from difflib import get_close_matches
from dotenv import load_dotenv
from openai import OpenAI
from pprint import pprint
import random
import re
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
from transformers import StoppingCriteria, StoppingCriteriaList
import torch.nn.functional as F

model_name = "mistral-7b-v0.1"

name2base = {"mistral-7b-v0.1":"mistralai/Mistral-7B-v0.1"}

base_model_name = name2base[model_name]
print("Loading ", base_model_name)
base_tokenizer = AutoTokenizer.from_pretrained(base_model_name)
base_tokenizer.pad_token = base_tokenizer.eos_token
base_model = AutoModelForCausalLM.from_pretrained(base_model_name, torch_dtype=torch.bfloat16, device_map="auto")
base_model.generation_config = GenerationConfig.from_pretrained(base_model_name)
base_model.generation_config.pad_token_id =base_model.generation_config.eos_token_id

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /scr/vvajipey/.cache/huggingface/token
Login successful
Loading  mistralai/Mistral-7B-v0.1


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [2]:
q_num = 1
n_samples = 3
answer_letter = 'B'

full_answer = torch.load(f"tensors/full_answer_tensors/columbus-csqa_q{q_num}_a{answer_letter}_n{n_samples}_logprobs.pt")
answer_mask = torch.load(f"tensors/answer_masks/columbus-csqa_q{q_num}_a{answer_letter}_n{n_samples}_answer_mask.pt")
instruct_log_probs = torch.load(f"tensors/instruct_log_probs/columbus-csqa_q{q_num}_a{answer_letter}_n{n_samples}_instruct_logprobs.pt")

In [3]:
base_tokenizer.batch_decode(full_answer * answer_mask)

['<unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk> The answer is (B). Sammy wanted to go to where the people were, and the most likely place for him to find a concentration of people would be in populated areas.</s>',
 '<unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk> The answer is (B). Sammy wanted to go to where the people were, so the best choice would be populated areas.</s></s><

In [4]:
import time

def sum_answer_logprobs(model, tokenizer, input_ids, answer_mask, batch_size=5, run_problem_name="nameless_logprobs", print_logging=False):
    input_ids = input_ids.to(model.device)
    answer_mask = answer_mask.to(model.device)

    start_time = time.time()
    total_summed_logprobs = torch.tensor([]).to(model.device)
    norm_total_summed_logprobs = torch.tensor([]).to(model.device)

    if print_logging:
        print("input_ids (rk_ai) shape: ", input_ids.shape)
        print("input_ids (rk_ai): ", input_ids)

    for i in range(0, input_ids.shape[0], batch_size):
        start_row_idx = i
        end_row_idx = min(i + batch_size, input_ids.shape[0])
        batch_ids = input_ids[start_row_idx:end_row_idx]

        with torch.no_grad():
            outputs = model(batch_ids)
        forward_pass_duration = time.time() - start_time
        if print_logging:
            print("Forward pass duration: ", forward_pass_duration)

        logprobs = torch.log_softmax(outputs.logits, dim=-1).detach()

        # Adjust indices to ignore the first token's log prob as it corresponds to the second token
        logprobs = logprobs[:, :-1, :]
        batch_ids  = batch_ids [:, 1:]

        # get logprobs corresponding to specific input_id tokens (out of all vocab logprob distribution)
        gen_logprobs = torch.gather(logprobs, 2, batch_ids[:, :, None]).squeeze(-1)

        SAVE_LOGPROBS = False
        if SAVE_LOGPROBS:
            torch.save(gen_logprobs, f"logprob_tensors/{run_problem_name}-logprobs.pt")

        masked_logprobs = gen_logprobs * answer_mask[start_row_idx:end_row_idx, 1:].float() # extract logprobs from answer tokens
        if print_logging:
            print("Answer Mask shape: ", answer_mask.shape)            
            print("Answer Mask: ", answer_mask)

        if print_logging:
            print("Masked logprobs shape: ", masked_logprobs.shape)
        nonzero_elements_count = (masked_logprobs != 0).sum(dim=1)
        if print_logging:
            print(masked_logprobs)
            print("Nonzero elements count per row (a_i length): ", nonzero_elements_count)

        batch_summed_logprobs = masked_logprobs.sum(dim=1)
        if print_logging:
            print("Batch summed logprobs: ", batch_summed_logprobs.shape, "\n", batch_summed_logprobs)

        total_summed_logprobs = torch.cat((total_summed_logprobs, batch_summed_logprobs), dim=0)
        norm_total_summed_logprobs = torch.cat((norm_total_summed_logprobs, batch_summed_logprobs / nonzero_elements_count), dim=0)
        
        if print_logging:
            print("summed_probs: ", batch_summed_logprobs.shape)

            # batch = []
            for input_sentence, input_probs in zip(batch_ids , masked_logprobs):
            # for input_sentence, input_probs in zip(batch_ids , gen_logprobs): # check all logprobs
                # text_sequence = []
                for token, p in zip(input_sentence, input_probs):
                    if token not in tokenizer.all_special_ids:
                        # print((tokenizer.decode(token), p.item()))
                        print(f"{tokenizer.decode(token)} ({token}): {p.item()}")
                        # text_sequence.append((tokenizer.decode(token), p.item()))
                # batch.append(text_sequence)

    # print("TOTAL SUMMED LOGPROBS: ", total_summed_logprobs)

    return total_summed_logprobs, norm_total_summed_logprobs

In [5]:
total_summed_logprobs, norm_total_summed_logprobs = sum_answer_logprobs(base_model, base_tokenizer, full_answer, answer_mask, batch_size=3, print_logging=True)

input_ids (rk_ai) shape:  torch.Size([3, 109])
input_ids (rk_ai):  tensor([[    1,   733, 16289, 28793, 22478, 28747,  4157,  1916,  2613,   298,
           576,   298,   970,   272,   905,   654, 28723, 28705,  6926,  1659,
           400,   576, 28804,    13,  2287, 25405,  1214, 28747,    13,  2287,
           325, 28741, 28731,  5941,  3508,    13,  2287,   325, 28760, 28731,
          1852,  6432,  5020,    13,  2287,   325, 28743, 28731,   272, 13453,
            13,  2287,   325, 28757, 28731,  9585,    13,  2287,   325, 28749,
         28731,  3878,  3356,    13,  2287, 26307, 28747,   733, 28748, 16289,
         28793,   415,  4372,   349,   325, 28760,   609,  4157,  1916,  2613,
           298,   576,   298,   970,   272,   905,   654, 28725,   304,   272,
          1080,  3917,  1633,   354,   713,   298,  1300,   264, 15987,   302,
           905,   682,   347,   297,  1852,  6432,  5020, 28723,     2],
        [    1,   733, 16289, 28793, 22478, 28747,  4157,  1916,  2613

In [6]:
total_summed_logprobs, norm_total_summed_logprobs

(tensor([-43.6933, -81.6929, -67.1124], device='cuda:0'),
 tensor([-1.1498, -2.1498, -1.7661], device='cuda:0'))

In [7]:
import csv

csv_file_path = f"logs/columbus_base_logprobs_{q_num}.csv"
file_exists = os.path.isfile(csv_file_path)

with open(csv_file_path, mode='a', newline='') as file:
    writer = csv.writer(file)
    
    if not file_exists:
        writer.writerow(["question_number", "answer_letter", "total_summed_logprobs", "norm_total_summed_logprobs"])
    for total_logprob, norm_logprob in zip(total_summed_logprobs.tolist(), norm_total_summed_logprobs.tolist()):
        writer.writerow([q_num, answer_letter, total_logprob, norm_logprob])