In [1]:
import os
os.environ['HF_HOME'] = '/scr/vvajipey/.cache/huggingface'
os.environ['HF_HUB'] = '/scr/vvajipey/.cache/huggingface'
from huggingface_hub import login
login("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")

import numpy as np
import os
import pandas as pd
import torch
from collections import Counter, defaultdict
from difflib import get_close_matches
from dotenv import load_dotenv
from openai import OpenAI
from pprint import pprint
import random
import re
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
from transformers import StoppingCriteria, StoppingCriteriaList
import torch.nn.functional as F

gsm_df = pd.read_csv('../distribution/data/gsm8kTest.csv')

model_name = "mistralai/Mistral-7B-Instruct-v0.1"
# model_name = "mistralai/Mistral-7B-Instruct-v0.3"
# model_name = "meta-llama/Meta-Llama-3-8B"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = 'left'

model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.bfloat16, device_map="auto")
model.generation_config = GenerationConfig.from_pretrained(model_name)
model.generation_config.pad_token_id = model.generation_config.eos_token_id

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /scr/vvajipey/.cache/huggingface/token
Login successful


/scr/vvajipey/miniconda3/envs/reason/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

/scr/vvajipey/miniconda3/envs/reason/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [10]:
import ast
train_df = pd.read_csv("data/commonsense_qa_train.csv")
train_df['choices'] = train_df['choices'].apply(ast.literal_eval)
train_df



id  \
0     075e483d21c29a511267ef62bedc0461   
1     61fe6e879ff18686d7552425a36344c8   
2     4c1cb0e95b99f72d55c068ba0255c54d   
3     02e821a3e53cb320790950aab4489e85   
4     23505889b94e880c3e89cff4ba119860   
...                                ...   
9736  f1b2a30a1facff543e055231c5f90dd0   
9737  a63b4d0c0b34d6e5f5ce7b2c2c08b825   
9738  22d0eea15e10be56024fd00bb0e4f72f   
9739  7c55160a4630de9690eb328b57a18dc2   
9740  dd640927f9920930501fb8dc3efc196b   

                                               question question_concept  \
0     The sanctions against the school were a punish...        punishing   
1     Sammy wanted to go to where the people were.  ...           people   
2     To locate a choker not located in a jewelry bo...           choker   
3     Google Maps and other highway and street GPS s...          highway   
4     The fox walked from the city into the forest, ...              fox   
...                                                 ...              ...   
9736  What would someone need to do if he or she wan...     going public   
9737         Where might you find a chair at an office?            chair   
9738  Where would you buy jeans in a place with a la...            jeans   
9739  John fell down the well.  he couldn't believe ...             well   
9740  I forgot to pay the electricity bill, now what...      electricity   

                                                choices answerKey  
0     {'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...         A  
1     {'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...         B  
2     {'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...         A  
3     {'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...         D  
4     {'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...         C  
...                                                 ...       ...  
9736  {'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...         E  
9737  {'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...         D  
9738  {'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...         A  
9739  {'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...         A  
9740  {'label': ['A', 'B', 'C', 'D', 'E'], 'text': [...         C  

[9741 rows x 5 columns]

In [15]:
def sample_completions_from_model(question, choices, tokenizer, n_samples=1):
    # https://arxiv.org/html/2402.17302v1
    
    prompt = f"""Question: {question}
    Choices:
    A. {choices[0]}
    B. {choices[1]}
    C. {choices[2]}
    D. {choices[3]}
    E. {choices[4]}
    Answer:"""
    chat = [{"role":"user", "content":prompt}]

    input_tensor = tokenizer.apply_chat_template(chat)

    for _ in range(n_samples):
        gen_outputs = model.generate(
            input_tensor.to(model.device),
            min_new_tokens=10,
            max_new_tokens=1000,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=True,
            temperature=0.7,
            top_k=40,
        ).sequences
    return new_paths, path_to_tensor

In [14]:
train_df['choices'][1]['text']

['race track', 'populated areas', 'the desert', 'apartment', 'roadblock']

In [25]:
prompt = f"""Question: {train_df['question'][1]}
    Choices:
    (A) {train_df['choices'][1]['text'][0]}
    (B) {train_df['choices'][1]['text'][1]}
    (C) {train_df['choices'][1]['text'][2]}
    (D) {train_df['choices'][1]['text'][3]}
    (E) {train_df['choices'][1]['text'][4]}
    Answer:"""
prompt

'Question: Sammy wanted to go to where the people were.  Where might he go?\n    Choices:\n    (A) race track\n    (B) populated areas\n    (C) the desert\n    (D) apartment\n    (E) roadblock\n    Answer:'

In [26]:
chat = [{"role":"user", "content":prompt}]

input_tensor = tokenizer.apply_chat_template(chat, return_tensors='pt')
tokenizer.apply_chat_template(chat, tokenize=False) 

'<s>[INST] Question: Sammy wanted to go to where the people were.  Where might he go?\n    Choices:\n    (A) race track\n    (B) populated areas\n    (C) the desert\n    (D) apartment\n    (E) roadblock\n    Answer: [/INST]'

In [29]:
gen_outputs = model.generate(
            input_tensor.to(model.device),
            min_new_tokens=10,
            max_new_tokens=1000,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=True,
            temperature=0.7,
            top_k=40,
        )

In [30]:
pprint(tokenizer.batch_decode(gen_outputs.sequences))

['<s> [INST] Question: Sammy wanted to go to where the people were.  Where '
 'might he go?\n'
 '    Choices:\n'
 '    (A) race track\n'
 '    (B) populated areas\n'
 '    (C) the desert\n'
 '    (D) apartment\n'
 '    (E) roadblock\n'
 '    Answer: [/INST] Sammy might go to where the people are, so the correct '
 'choice would be (B) populated areas.</s>']


In [31]:
transition_scores = model.compute_transition_scores(
    gen_outputs.sequences, gen_outputs.scores, normalize_logits=True
)
transition_scores

tensor([[-1.2758e-01,  0.0000e+00, -3.8946e-01, -1.9602e-02, -5.8768e-05,
         -3.8944e+00, -1.0339e-01, -2.3374e-04, -1.1094e-01, -9.0137e-02,
         -3.1514e-01, -1.1663e-01, -1.7940e+00, -1.5629e-01, -2.5322e-01,
         -1.7047e-05, -3.9002e-03, -1.9322e-03, -1.1921e-07, -5.1259e-05,
          0.0000e+00,  0.0000e+00, -1.9518e-03, -2.8916e-04]], device='cuda:0')

In [33]:
input_length = input_tensor.shape[1]
input_length

71

In [36]:
generated_tokens = gen_outputs.sequences[:, input_length:]
for tok, score in zip(generated_tokens[0], transition_scores[0]):
    # | token | token string | logits | probability
    print(f"| {tok:5d} | {tokenizer.decode(tok):8s} | {score.cpu().numpy():.4f} | {np.exp(score.cpu().numpy()):.2%}")

|  4157 | Sam      | -0.1276 | 88.02%
|  1916 | my       | 0.0000 | 100.00%
|  1659 | might    | -0.3895 | 67.74%
|   576 | go       | -0.0196 | 98.06%
|   298 | to       | -0.0001 | 99.99%
|   970 | where    | -3.8944 | 2.04%
|   272 | the      | -0.1034 | 90.18%
|   905 | people   | -0.0002 | 99.98%
|   460 | are      | -0.1109 | 89.50%
| 28725 | ,        | -0.0901 | 91.38%
|   579 | so       | -0.3151 | 72.97%
|   272 | the      | -0.1166 | 88.99%
|  4714 | correct  | -1.7940 | 16.63%
|  4782 | choice   | -0.1563 | 85.53%
|   682 | would    | -0.2532 | 77.63%
|   347 | be       | -0.0000 | 100.00%
|   325 | (        | -0.0039 | 99.61%
| 28760 | B        | -0.0019 | 99.81%
| 28731 | )        | -0.0000 | 100.00%
|  1852 | pop      | -0.0001 | 99.99%
|  6432 | ulated   | 0.0000 | 100.00%
|  5020 | areas    | 0.0000 | 100.00%
| 28723 | .        | -0.0020 | 99.81%
|     2 | </s>     | -0.0003 | 99.97%


In [47]:
letters = tokenizer.encode("(A)_(B)_(C)_(D)_(E)\n A A\n An Answer a B C D E")
for tok in letters:
    print(f"{tok} = '{tokenizer.decode(tok)}'")

1 = '<s>'
325 = '('
28741 = 'A'
28731 = ')'
10653 = '_('
28760 = 'B'
28731 = ')'
10653 = '_('
28743 = 'C'
28731 = ')'
10653 = '_('
28757 = 'D'
28731 = ')'
10653 = '_('
28749 = 'E'
28731 = ')'
13 = '
'
330 = 'A'
330 = 'A'
13 = '
'
1094 = 'An'
26307 = 'Answer'
264 = 'a'
365 = 'B'
334 = 'C'
384 = 'D'
413 = 'E'


In [50]:
output_tensor = gen_outputs.sequences

answer_to_tok = {'A':[28741, 330], 'B':[28760, 365], 'C':[28743, 334], 'D':[28757, 384], 'E':[28749, 413]}

masked_output_tensor = torch.where(
    torch.isin(output_tensor, torch.tensor(answer_to_tok['B'], device=output_tensor.device)),
    output_tensor,
    torch.tensor(0, device=output_tensor.device)
)
masked_output_tensor

tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0, 28760,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0, 28760,     0,
             0,     0,     0,     0,     0]], device='cuda:0')

In [52]:
generated_tokens = masked_output_tensor[:, input_length:]
for tok, score in zip(generated_tokens[0], transition_scores[0]):
    # | token | token string | logits | probability
    print(f"| {tok:5d} | {tokenizer.decode(tok):8s} | {score.cpu().numpy():.4f} | {np.exp(score.cpu().numpy()):.2%}")

|     0 | <unk>    | -0.1276 | 88.02%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | -0.3895 | 67.74%
|     0 | <unk>    | -0.0196 | 98.06%
|     0 | <unk>    | -0.0001 | 99.99%
|     0 | <unk>    | -3.8944 | 2.04%
|     0 | <unk>    | -0.1034 | 90.18%
|     0 | <unk>    | -0.0002 | 99.98%
|     0 | <unk>    | -0.1109 | 89.50%
|     0 | <unk>    | -0.0901 | 91.38%
|     0 | <unk>    | -0.3151 | 72.97%
|     0 | <unk>    | -0.1166 | 88.99%
|     0 | <unk>    | -1.7940 | 16.63%
|     0 | <unk>    | -0.1563 | 85.53%
|     0 | <unk>    | -0.2532 | 77.63%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0039 | 99.61%
| 28760 | B        | -0.0019 | 99.81%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0001 | 99.99%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | -0.0020 | 99.81%
|     0 | <unk>    | -0.0003 | 99.97%


In [54]:
transition_scores.shape

torch.Size([1, 24])

In [55]:
generated_tokens.shape

torch.Size([1, 24])

In [53]:
non_zero_values = masked_output_tensor[masked_output_tensor != 0]
non_zero_values

tensor([28760, 28760], device='cuda:0')

In [60]:
answer_mask = torch.isin(generated_tokens, torch.tensor(answer_to_tok['B'], device=output_tensor.device)).int()
masked_generated_tokens = generated_tokens * answer_mask
masked_generated_tokens

tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0, 28760,     0,     0,
             0,     0,     0,     0]], device='cuda:0')

In [63]:
masked_log_probs = transition_scores * answer_mask
for tok, score in zip(masked_generated_tokens[0], masked_log_probs[0]):
    # | token | token string | logits | probability
    print(f"| {tok:5d} | {tokenizer.decode(tok):8s} | {score.cpu().numpy():.4f} | {np.exp(score.cpu().numpy()):.2%}")

|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
| 28760 | B        | -0.0019 | 99.81%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | 0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%
|     0 | <unk>    | -0.0000 | 100.00%


In [49]:
for c in "ABCDE":
    print(c)
    print(answer_to_tok[c])
    print(tokenizer.batch_decode(answer_to_tok[c]))

A
[28741, 330]
['A', 'A']
B
[28760, 365]
['B', 'B']
C
[28743, 334]
['C', 'C']
D
[28757, 384]
['D', 'D']
E
[28749, 413]
['E', 'E']


In [70]:
# b_tensor = tokenizer.batch_decode(tokenizer.encode(tokenizer.apply_chat_template(chat, tokenize=False) + " The answer is (B).", return_tensors='pt', add_special_tokens=False))
b_tensor = tokenizer.encode(tokenizer.apply_chat_template(chat, tokenize=False) + " The answer is (B).", return_tensors='pt', add_special_tokens=False)

In [71]:
b_outputs = model.generate(
            b_tensor.to(model.device),
            min_new_tokens=10,
            max_new_tokens=1000,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=True,
            temperature=0.7,
            top_k=40,
        )

In [76]:
tokenizer.batch_decode(b_outputs.sequences)

['<s> [INST] Question: Sammy wanted to go to where the people were.  Where might he go?\n    Choices:\n    (A) race track\n    (B) populated areas\n    (C) the desert\n    (D) apartment\n    (E) roadblock\n    Answer: [/INST] The answer is (B). Sammy wanted to go to where the people were, and the best option among the given choices is the populated areas, where he is likely to find a large number of people.</s>']

In [77]:
b_output_tensor = b_outputs.sequences

In [79]:
tokenizer.batch_decode(b_output_tensor[:, b_tensor.shape[1]:])

['Sammy wanted to go to where the people were, and the best option among the given choices is the populated areas, where he is likely to find a large number of people.</s>']

Pipeline

In [80]:
prompt = f"""Question: {train_df['question'][1]}
    Choices:
    (A) {train_df['choices'][1]['text'][0]}
    (B) {train_df['choices'][1]['text'][1]}
    (C) {train_df['choices'][1]['text'][2]}
    (D) {train_df['choices'][1]['text'][3]}
    (E) {train_df['choices'][1]['text'][4]}
    Answer:"""

answer_prefix = tokenizer.encode(tokenizer.apply_chat_template(chat, tokenize=False) + " The answer is (B).", return_tensors='pt', add_special_tokens=False)

outputs = model.generate(
            answer_prefix.to(model.device),
            min_new_tokens=10,
            max_new_tokens=1000,
            return_dict_in_generate=True,
            output_scores=True,
            do_sample=True,
            temperature=0.7,
            top_k=40,
        )

In [88]:
full_answer = outputs.sequences
full_answer

tensor([[    1,   733, 16289, 28793, 22478, 28747,  4157,  1916,  2613,   298,
           576,   298,   970,   272,   905,   654, 28723, 28705,  6926,  1659,
           400,   576, 28804,    13,  2287, 25405,  1214, 28747,    13,  2287,
           325, 28741, 28731,  5941,  3508,    13,  2287,   325, 28760, 28731,
          1852,  6432,  5020,    13,  2287,   325, 28743, 28731,   272, 13453,
            13,  2287,   325, 28757, 28731,  9585,    13,  2287,   325, 28749,
         28731,  3878,  3356,    13,  2287, 26307, 28747,   733, 28748, 16289,
         28793,   415,  4372,   349,   325, 28760,   609,  4157,  1916,  2613,
           298,   576,   298,   970,   272,   905,   654, 28725,   579,   272,
          1489,  4782,   682,   347,   298,   576,   298,  1852,  6432,  5020,
         28723,     2]], device='cuda:0')

In [90]:
# INST is 16289
tokenizer.decode(16289)

'INST'

In [98]:
def find_last_occurrence(tensor, target, offset=2):
    mask = (tensor == target)
    last_occurrence_indices = torch.full((tensor.shape[0],), -1, dtype=torch.long)
    
    for i in range(tensor.shape[0]):
        indices = torch.nonzero(mask[i], as_tuple=False).squeeze()
        if indices.numel() > 0:
            last_occurrence_indices[i] = indices[-1].item() + offset
    
    return last_occurrence_indices

find_last_occurrence(full_answer, 16289)

tensor([71])

In [101]:
def mask_before_last_occurrence(tensor, target, offset=2):
    # Find the last occurrence indices
    last_occurrence_indices = find_last_occurrence(tensor, target, offset)
    
    # Create a mask tensor filled with ones
    mask = torch.ones_like(tensor, dtype=torch.bool)
    
    # Initialize a list to store the count of masked tokens for each row
    masked_tokens_count = []
    
    # Apply the mask for each row based on the last occurrence index
    for i in range(tensor.shape[0]):
        if last_occurrence_indices[i] != -1:  # Check if the target is present in the row
            mask[i, :last_occurrence_indices[i]] = 0  # Mask out all values before the last occurrence
            masked_count = last_occurrence_indices[i]  # Count of masked tokens
        else:
            masked_count = 0  # No tokens masked if the target is not found in the row
        masked_tokens_count.append(masked_count)
    
    # Apply the mask to the original tensor
    masked_tensor = tensor * mask
    
    return masked_tensor, masked_tokens_count

In [104]:
answer_tensor, prefix_lengths = mask_before_last_occurrence(full_answer, 16289)
answer_tensor, tokenizer.batch_decode(answer_tensor[:, prefix_lengths[0]:])

(tensor([[    0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,   415,  4372,   349,   325, 28760,   609,  4157,  1916,  2613,
            298,   576,   298,   970,   272,   905,   654, 28725,   579,   272,
           1489,  4782,   682,   347,   298,   576,   298,  1852,  6432,  5020,
          28723,     2]], device='cuda:0'),
 ['The answer is (B). Sammy wanted to go to where the people were, so the best choice would be to go to populated areas.</s>'])

In [108]:
full_answer.shape[1] - answer_prefix.shape[1]

25

In [112]:
instruct_log_probs = model.compute_transition_scores(
    outputs.sequences, outputs.scores, normalize_logits=True
)
instruct_log_probs

tensor([[-2.0739e-03,  0.0000e+00, -1.0460e-01, -8.3446e-07, -2.1458e-06,
         -3.2990e-03, -5.6334e-01, -3.6283e-03, -3.0994e-06, -3.0994e-06,
         -3.0695e-03, -2.8968e-01, -2.5802e-01, -1.0032e+00, -3.4426e-01,
         -1.0220e-01, -4.0292e-05, -2.3906e+00, -2.9752e-01, -1.7881e-06,
         -6.6615e-02,  0.0000e+00,  0.0000e+00, -3.0647e-02, -5.6161e-02]],
       device='cuda:0')