In [1]:
import os
os.environ['HF_HOME'] = '/scr/vvajipey/.cache/huggingface'
os.environ['HF_HUB'] = '/scr/vvajipey/.cache/huggingface'
from huggingface_hub import login
login("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")

import ast
import numpy as np
import os
import pandas as pd
import torch
from collections import Counter, defaultdict
from difflib import get_close_matches
from pprint import pprint
import random
import re
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
from transformers import StoppingCriteria, StoppingCriteriaList
import torch.nn.functional as F

model_name = "mistral-7b-v0.1"

name2base = {"mistral-7b-v0.1":"mistralai/Mistral-7B-v0.1"}
name2instruct = {"mistral-7b-v0.1": "mistralai/Mistral-7B-Instruct-v0.1"}

base_model_name = name2base[model_name]
print("Loading ", base_model_name)
base_tokenizer = AutoTokenizer.from_pretrained(base_model_name)
base_tokenizer.pad_token = base_tokenizer.eos_token
base_model = AutoModelForCausalLM.from_pretrained(base_model_name, torch_dtype=torch.bfloat16, device_map="auto")
base_model.generation_config = GenerationConfig.from_pretrained(base_model_name)
base_model.generation_config.pad_token_id =base_model.generation_config.eos_token_id

name2instruct = {"mistral-7b-v0.1": "mistralai/Mistral-7B-Instruct-v0.1"}
instruct_model_name = name2instruct[model_name]
instruct_tokenizer = AutoTokenizer.from_pretrained(instruct_model_name)
instruct_tokenizer.pad_token = instruct_tokenizer.eos_token

Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /scr/vvajipey/.cache/huggingface/token
Login successful
Loading  mistralai/Mistral-7B-v0.1


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [15]:
# prompt = """A B C
# A B C

# X Y Z
# X Y 
# """

# prompt = "Complete the sequence: A, B, C, __."
prompt = "1 + 1 = "

prompt_tensor = base_tokenizer.encode(prompt, return_tensors='pt')
print([(n, base_tokenizer.decode(n)) for n in list(n.item() for n in prompt_tensor.flatten())])

n_samples = 3
prompt_tensor = prompt_tensor.repeat(n_samples, 1)
prompt_tensor.shape

[(1, '<s>'), (28705, ''), (28740, '1'), (648, '+'), (28705, ''), (28740, '1'), (327, '='), (28705, '')]


torch.Size([3, 8])

In [16]:
temp = 1.0
top_k = 50

outputs = base_model.generate(
                    prompt_tensor.to(base_model.device),
                    min_new_tokens=0,
                    max_new_tokens=2,
                    return_dict_in_generate=True,
                    output_scores=True,
                    do_sample=True,
                    temperature=1.0,
                    top_k=50,
                )

In [17]:
for s in base_tokenizer.batch_decode(outputs.sequences):
    pprint(s)

'<s> 1 + 1 = 2\n'
'<s> 1 + 1 = 2.'
'<s> 1 + 1 = 39'


In [18]:
outputs.sequences.shape

torch.Size([3, 10])

In [19]:
og_log_probs = base_model.compute_transition_scores(outputs.sequences, outputs.scores, normalize_logits=True)
og_log_probs

tensor([[-0.6725, -1.1066],
        [-0.6725, -1.6066],
        [-1.3600, -6.5624]], device='cuda:0')

In [20]:
with torch.no_grad():
    scores = base_model(outputs.sequences)

scores.logits.shape
logits = scores.logits

In [21]:
vocab_scored_logprobs = torch.log_softmax(logits, dim=-1).detach()
vocab_scored_logprobs = vocab_scored_logprobs[:, :-1, :]
token_ids = outputs.sequences[:, 1:]

In [22]:
base_tokenizer.batch_decode(token_ids)

['1 + 1 = 2\n', '1 + 1 = 2.', '1 + 1 = 39']

In [23]:
scored_logprobs = torch.gather(vocab_scored_logprobs, 2, token_ids[:, :, None]).squeeze(-1)
for input_sentence, input_probs in zip(token_ids , scored_logprobs):
    # for input_sentence, input_probs in zip(batch_ids , gen_logprobs): # check all logprobs
    print("---sequence---")
    for token, p in zip(input_sentence, input_probs):
        # if token not in base_tokenizer.all_special_ids:
        pprint(f"{base_tokenizer.decode(token)} ({token}): {p.item()}")

---sequence---
' (28705): -4.431795120239258'
'1 (28740): -0.975562334060669'
'+ (648): -9.606401443481445'
' (28705): -0.7148184776306152'
'1 (28740): -0.33568018674850464'
'= (327): -0.4048469364643097'
' (28705): -0.21074119210243225'
'2 (28750): -0.6747506856918335'
'\n (13): -1.2522019147872925'
---sequence---
' (28705): -4.431795120239258'
'1 (28740): -0.975562334060669'
'+ (648): -9.606401443481445'
' (28705): -0.7148184776306152'
'1 (28740): -0.33568018674850464'
'= (327): -0.4048469364643097'
' (28705): -0.21074119210243225'
'2 (28750): -0.6747506856918335'
'. (28723): -1.6897019147872925'
---sequence---
' (28705): -4.431795120239258'
'1 (28740): -0.975562334060669'
'+ (648): -9.606401443481445'
' (28705): -0.7148184776306152'
'1 (28740): -0.33568018674850464'
'= (327): -0.4048469364643097'
' (28705): -0.21074119210243225'
'3 (28770): -1.3622506856918335'
'9 (28774): -6.713685989379883'


In [26]:
scored_logprobs [:, -2:]

tensor([[-0.6748, -1.2522],
        [-0.6748, -1.6897],
        [-1.3623, -6.7137]], device='cuda:0')

Experiment: Marginalizing over B_i

In [39]:
def score_sequence(tensor, model, tokenizer, print_logging=False):
    tensor = tensor.to(model.device)
    
    with torch.no_grad():
        scores = model(tensor)

    scores.logits.shape
    logits = scores.logits
    vocab_scored_logprobs = torch.log_softmax(logits, dim=-1).detach()
    vocab_scored_logprobs = vocab_scored_logprobs[:, :-1, :]
    token_ids = tensor[:, 1:]
    scored_logprobs = torch.gather(vocab_scored_logprobs, 2, token_ids[:, :, None]).squeeze(-1)
    
    if print_logging:
        for input_sentence, input_probs in zip(token_ids , scored_logprobs):
            # for input_sentence, input_probs in zip(batch_ids , gen_logprobs): # check all logprobs
            print("---sequence---")
            for token, p in zip(input_sentence, input_probs):
                # if token not in base_tokenizer.all_special_ids:
                pprint(f"{tokenizer.decode(token)} ({token}): {p.item()}")

    return scored_logprobs.sum(dim=1)

In [30]:
prompt = "1 + 1 = "

prompt_tensor = base_tokenizer.encode(prompt, return_tensors='pt')
print([(n, base_tokenizer.decode(n)) for n in list(n.item() for n in prompt_tensor.flatten())])
prompt_tensor.shape

[(1, '<s>'), (28705, ''), (28740, '1'), (648, '+'), (28705, ''), (28740, '1'), (327, '='), (28705, '')]


torch.Size([1, 8])

In [49]:
prob_A = score_sequence(prompt_tensor, base_model, base_tokenizer, print_logging=True)
prob_A

---sequence---
' (28705): -4.384565353393555'
'1 (28740): -0.9495829343795776'
'+ (648): -9.594989776611328'
' (28705): -0.6903921961784363'
'1 (28740): -0.32114025950431824'
'= (327): -0.39957746863365173'
' (28705): -0.209198459982872'


tensor([-16.5494], device='cuda:0')

In [54]:
n_samples = 3
prompt_tensor = prompt_tensor.repeat(n_samples, 1)
prompt_tensor.shape

torch.Size([3, 8])

In [55]:
temp = 1.0
top_k = 50

completions = base_model.generate(
                    prompt_tensor.to(base_model.device),
                    min_new_tokens=0,
                    max_new_tokens=2,
                    return_dict_in_generate=True,
                    output_scores=True,
                    do_sample=True,
                    temperature=1.0,
                    top_k=50,
                )

In [56]:
prob_A_B = score_sequence(completions.sequences, base_model, base_tokenizer, print_logging=True)
prob_A_B

---sequence---
' (28705): -4.431795120239258'
'1 (28740): -0.975562334060669'
'+ (648): -9.606401443481445'
' (28705): -0.7148184776306152'
'1 (28740): -0.33568018674850464'
'= (327): -0.4048469364643097'
' (28705): -0.21074119210243225'
'0 (28734): -4.299750804901123'
'. (28723): -1.7196247577667236'
---sequence---
' (28705): -4.431795120239258'
'1 (28740): -0.975562334060669'
'+ (648): -9.606401443481445'
' (28705): -0.7148184776306152'
'1 (28740): -0.33568018674850464'
'= (327): -0.4048469364643097'
' (28705): -0.21074119210243225'
'2 (28750): -0.6747506856918335'
'is (349): -2.877202033996582'
---sequence---
' (28705): -4.431795120239258'
'1 (28740): -0.975562334060669'
'+ (648): -9.606401443481445'
' (28705): -0.7148184776306152'
'1 (28740): -0.33568018674850464'
'= (327): -0.4048469364643097'
' (28705): -0.21074119210243225'
'2 (28750): -0.6747506856918335'
'\n (13): -1.2522019147872925'


tensor([-22.6992, -20.2318, -18.6068], device='cuda:0')

In [57]:
torch.logsumexp(prob_A_B, dim=0)

tensor(-18.4132, device='cuda:0')